import { registerEnumType } from "type-graphql";

export enum Region {
    ALL = "ALL",

    NORTH = "NORTH",
    SOUTH = "SOUTH",
    INTERNATIONAL = "INTERNATIONAL",

    AU = "AU",
    BR = "BR",
    CAAB = "CAAB",
    CABC = "CABC",
    CAON = "CAON",
    CAQC = "CAQC",
    CMPZ2 = "CMPZ2",
    CN = "CN",
    CY = "CY",
    EG = "EG",
    GB = "GB",
    IL = "IL",
    IN = "IN",
    JM = "JM",
    KZ = "KZ",
    LY = "LY",
    MX = "MX",
    NG = "NG",
    NL = "NL",
    ONADOD = "ONADOD",
    QA = "QA",
    RO = "RO",
    RU = "RU",
    TH = "TH",
    TW = "TW",
    USAK = "USAK",
    USAL = "USAL",
    USAR = "USAR",
    USARL = "USARL",
    USAZ = "USAZ",
    USCALA = "USCALA",
    USCANO = "USCANO",
    USCASD = "USCASD",
    USCHS = "USCHS",
    USCO = "USCO",
    USCT = "USCT",
    USDE = "USDE",
    USFL = "USFL",
    USGA = "USGA",
    USHI = "USHI",
    USIA = "USIA",
    USID = "USID",
    USIL = "USIL",
    USIN = "USIN",
    USKY = "USKY",
    USLA = "USLA",
    USMA = "USMA",
    USMI = "USMI",
    USMN = "USMN",
    USMOKS = "USMOKS",
    USMS = "USMS",
    USMT = "USMT",
    USNC = "USNC",
    USND = "USND",
    USNH = "USNH",
    USNJ = "USNJ",
    USNM = "USNM",
    USNV = "USNV",
    USNYEX = "USNYEX",
    USNYLI = "USNYLI",
    USNYNY = "USNYNY",
    USOH = "USOH",
    USOK = "USOK",
    USOR = "USOR",
    USPA = "USPA",
    USRI = "USRI",
    USSC = "USSC",
    USTN = "USTN",
    USTXCE = "USTXCE",
    USTXHO = "USTXHO",
    USTXNO = "USTXNO",
    USTXSO = "USTXSO",
    USTXWP = "USTXWP",
    USUT = "USUT",
    USVT = "USVT",
    USWA = "USWA",
    USWI = "USWI",
    USWY = "USWY",
    ZA = "ZA",
}

registerEnumType(Region, {
    name: "Region",
});

export function getRegionCodes(region: Region): string[] {
    switch (region) {
        case Region.ALL:
            return ALL_REGIONS;
        case Region.NORTH:
            return NORTH_REGIONS;
        case Region.SOUTH:
            return SOUTH_REGIONS;
        case Region.INTERNATIONAL:
            return INTERNATIONAL_REGIONS;
        default:
            return [region.toString()];
    }
}

let ALL_REGIONS = [
    Region.AU,
    Region.BR,
    Region.CAAB,
    Region.CABC,
    Region.CAON,
    Region.CAQC,
    Region.CMPZ2,
    Region.CN,
    Region.CY,
    Region.EG,
    Region.GB,
    Region.IL,
    Region.IN,
    Region.JM,
    Region.KZ,
    Region.LY,
    Region.MX,
    Region.NG,
    Region.NL,
    Region.ONADOD,
    Region.QA,
    Region.RO,
    Region.RU,
    Region.TH,
    Region.TW,
    Region.USAK,
    Region.USAL,
    Region.USAR,
    Region.USARL,
    Region.USAZ,
    Region.USCALA,
    Region.USCANO,
    Region.USCASD,
    Region.USCHS,
    Region.USCO,
    Region.USCT,
    Region.USDE,
    Region.USFL,
    Region.USGA,
    Region.USHI,
    Region.USIA,
    Region.USID,
    Region.USIL,
    Region.USIN,
    Region.USKY,
    Region.USLA,
    Region.USMA,
    Region.USMI,
    Region.USMN,
    Region.USMOKS,
    Region.USMS,
    Region.USMT,
    Region.USNC,
    Region.USND,
    Region.USNH,
    Region.USNJ,
    Region.USNM,
    Region.USNV,
    Region.USNYEX,
    Region.USNYLI,
    Region.USNYNY,
    Region.USOH,
    Region.USOK,
    Region.USOR,
    Region.USPA,
    Region.USRI,
    Region.USSC,
    Region.USTN,
    Region.USTXCE,
    Region.USTXHO,
    Region.USTXNO,
    Region.USTXSO,
    Region.USTXWP,
    Region.USUT,
    Region.USVT,
    Region.USWA,
    Region.USWI,
    Region.USWY,
    Region.ZA,
].map((r) => r.toString());

let NORTH_REGIONS = [
    Region.USCT,
    Region.USDE,
    Region.USIA,
    Region.USIL,
    Region.USIN,
    Region.USKY,
    Region.USMA,
    Region.USCHS,
    Region.USMN,
    Region.USND,
    Region.USNH,
    Region.USNJ,
    Region.USNYEX,
    Region.USNYLI,
    Region.USNYNY,
    Region.USOH,
    Region.USPA,
    Region.USRI,
    Region.USVT,
    Region.USWI,
    Region.USMI,
].map((r) => r.toString());

let SOUTH_REGIONS = [
    Region.USAK,
    Region.USAL,
    Region.USAR,
    Region.USAZ,
    Region.USCALA,
    Region.USCANO,
    Region.USCASD,
    Region.USCO,
    Region.USFL,
    Region.USGA,
    Region.USHI,
    Region.USID,
    Region.USMOKS,
    Region.USLA,
    Region.USMS,
    Region.USMT,
    Region.USNC,
    Region.USNM,
    Region.USNV,
    Region.USOK,
    Region.USOR,
    Region.USSC,
    Region.USTN,
    Region.USTXCE,
    Region.USTXHO,
    Region.USTXNO,
    Region.USTXSO,
    Region.USTXWP,
    Region.USUT,
    Region.USWA,
    Region.USWY,
].map((r) => r.toString());

let INTERNATIONAL_REGIONS = [
    Region.CAAB,
    Region.AU,
    Region.CABC,
    Region.IL,
    Region.JM,
    Region.KZ,
    Region.ONADOD,
    Region.MX,
    Region.NL,
    Region.CAON,
    Region.QA,
    Region.RO,
    Region.RU,
    Region.TH,
    Region.TW,
    Region.ZA,
    Region.BR,
    Region.CAQC,
    Region.CN,
    Region.CY,
    Region.EG,
    Region.GB,
    Region.IN,
    Region.LY,
    Region.NG,
].map((r) => r.toString());
