import { INTERNATIONAL_REGIONS, RegionOption } from "@ftc-scout/common";

const REGION_NAMES: Record<RegionOption, string> = {
    All: "All",

    UnitedStates: "United States",
    International: "International",

    // cspell:ignoreRegExp [A-Z\d]+:
    // cspell:ignore LAUSD, Québec
    USAK: "Alaska",
    USAL: "Alabama",
    USAR: "Arkansas",
    USAZ: "Arizona",
    USCA: "California",
    USCALA: "California - Los Angeles",
    USCALS: "California - LAUSD",
    USCANO: "California - Northern",
    USCASD: "California - San Diego",
    USCHS: "Chesapeake",
    USCO: "Colorado",
    USCT: "Connecticut",
    USDE: "Delaware",
    USFCT: "Four Corners",
    USFL: "Florida",
    USGA: "Georgia",
    USHI: "Hawaii",
    USIA: "Iowa",
    USID: "Idaho",
    USIL: "Illinois",
    USIN: "Indiana",
    USKY: "Kentucky",
    USLA: "Louisiana",
    USMA: "Massachusets",
    USMD: "Maryland",
    USMI: "Michigan",
    USMN: "Minnesota",
    USMOKS: "Missouri & Kansas",
    USMS: "Mississippi",
    USMT: "Montana",
    USNC: "North Carolina",
    USND: "North Dakota",
    USNE: "Nebraska",
    USNH: "New Hampshire",
    USNJ: "New Jersey",
    USNM: "New Mexico",
    USNV: "Nevada",
    USNY: "New York",
    USNYEX: "New York - Excelsior",
    USNYLI: "New York - Long Island",
    USNYNY: "New York - NYC",
    USOH: "Ohio",
    USOK: "Oklahoma",
    USOR: "Oregon",
    USPA: "Pennsylvania",
    USPR: "Puerto Rico",
    USRI: "Rhode Island",
    USSC: "South Carolina",
    USTN: "Tennessee",
    USTX: "Texas",
    USTXCE: "Texas - Central",
    USTXHO: "Texas - Houston",
    USTXNO: "Texas - North",
    USTXSO: "Texas - South",
    USTXWP: "Texas - West & Panhandle",
    USUT: "Utah",
    USVA: "Virginia",
    USVT: "Vermont",
    USWA: "Washington",
    USWI: "Wisconsin",
    USWV: "West Virginia",
    USWY: "Wyoming",

    CAAB: "Alberta",
    CABC: "British Columbia",
    CANL: "Newfoundland and Labrador",
    CAON: "Ontario",
    CAQC: "Québec",

    AE: "United Arab Emirates",
    AR: "Argentina",
    AU: "Australia",
    BR: "Brazil",
    CN: "China",
    CO: "Colombia",
    CY: "Cyprus",
    DE: "Germany",
    EC: "Ecuador",
    ECB: "Eastern Caribbean",
    EG: "Egypt",
    ES: "Spain",
    FR: "France",
    GB: "Great Britain",
    GR: "Greece",
    HKG: "Hong Kong",
    HT: "Haiti",
    HU: "Hungary",
    ID: "Indonesia",
    IL: "Israel",
    IN: "India",
    IT: "Italy",
    JM: "Jamaica",
    JP: "Japan",
    KR: "South Korea",
    KW: "Kuwait",
    KZ: "Kazakhstan",
    LT: "Lithuania",
    LY: "Libya",
    MA: "Morocco",
    MD: "Moldova",
    MX: "Mexico",
    MY: "Malaysia",
    NG: "Nigeria",
    NL: "Netherlands",
    NZ: "New Zealand",
    PA: "Panama",
    PL: "Poland",
    PT: "Portugal",
    PY: "Paraguay",
    QA: "Qatar",
    RO: "Romania",
    RU: "Russia",
    SA: "Saudi Arabia",
    SV: "El Salvador",
    TH: "Thailand",
    TR: "Turkey",
    TT: "Trinidad and Tobago",
    TW: "Taiwan",
    UA: "Ukraine",
    VE: "Venezuela",
    VN: "Vietnam",
    ZA: "South Africa",

    CMPIC: "Innovation Challenge",
    CMPZ2: "FIRST Championship",
    FPE: "Premier Event",
    IND: "Independent",
    ONADOD: "Military & Diplomatic",
    USARL: "Adventist Robotics League",
    // cspell:enable
};

export function regionName(option: RegionOption): string {
    return REGION_NAMES[option];
}

export function regionMatches(option: RegionOption, code: string): boolean {
    switch (option) {
        case RegionOption.All:
            return true;
        case RegionOption.UnitedStates:
            return code.startsWith("US");
        case RegionOption.International:
            return (INTERNATIONAL_REGIONS as string[]).indexOf(code) != -1;
        case RegionOption.USCA:
        case RegionOption.USTX:
        case RegionOption.USNY:
            return code.startsWith(option);
        default:
            return option == code;
    }
}

export const REGION_GROUPS: RegionOption[][] = [
    [RegionOption.All, RegionOption.UnitedStates, RegionOption.International],

    // cspell:ignoreRegExp RegionOption\.[A-Z\d]+
    [
        RegionOption.USAK,
        RegionOption.USAL,
        RegionOption.USAR,
        RegionOption.USAZ,
        RegionOption.USCA,
        RegionOption.USCALA,
        RegionOption.USCALS,
        RegionOption.USCANO,
        RegionOption.USCASD,
        RegionOption.USCHS,
        RegionOption.USCO,
        RegionOption.USCT,
        RegionOption.USDE,
        RegionOption.USFCT,
        RegionOption.USFL,
        RegionOption.USGA,
        RegionOption.USHI,
        RegionOption.USIA,
        RegionOption.USID,
        RegionOption.USIL,
        RegionOption.USIN,
        RegionOption.USKY,
        RegionOption.USLA,
        RegionOption.USMA,
        RegionOption.USMD,
        RegionOption.USMI,
        RegionOption.USMN,
        RegionOption.USMOKS,
        RegionOption.USMS,
        RegionOption.USMT,
        RegionOption.USNC,
        RegionOption.USND,
        RegionOption.USNE,
        RegionOption.USNH,
        RegionOption.USNJ,
        RegionOption.USNM,
        RegionOption.USNV,
        RegionOption.USNY,
        RegionOption.USNYEX,
        RegionOption.USNYLI,
        RegionOption.USNYNY,
        RegionOption.USOH,
        RegionOption.USOK,
        RegionOption.USOR,
        RegionOption.USPA,
        RegionOption.USPR,
        RegionOption.USRI,
        RegionOption.USSC,
        RegionOption.USTN,
        RegionOption.USTX,
        RegionOption.USTXCE,
        RegionOption.USTXHO,
        RegionOption.USTXNO,
        RegionOption.USTXSO,
        RegionOption.USTXWP,
        RegionOption.USUT,
        RegionOption.USVA,
        RegionOption.USVT,
        RegionOption.USWA,
        RegionOption.USWI,
        RegionOption.USWV,
        RegionOption.USWY,
    ],

    [RegionOption.CAAB, RegionOption.CABC, RegionOption.CANL, RegionOption.CAON, RegionOption.CAQC],

    INTERNATIONAL_REGIONS,

    [
        RegionOption.CMPIC,
        RegionOption.CMPZ2,
        RegionOption.FPE,
        RegionOption.IND,
        RegionOption.ONADOD,
        RegionOption.USARL,
    ],
];
