export interface AllianceScores2023TradFtcApi {
    alliance: "Blue" | "Red";
    team: number;
    sideOfField: string | "SCORING_SIDE";
    initTeamProp1: boolean;
    initTeamProp2: boolean;
    robot1Auto: boolean;
    robot2Auto: boolean;
    spikeMarkPixel1: boolean;
    spikeMarkPixel2: boolean;
    targetBackdropPixel1: boolean;
    targetBackdropPixel2: boolean;
    autoBackdrop: number;
    autoBackstage: number;
    dcBackdrop: number;
    dcStudio: number;
    mosaics: number;
    maxSetLine: number;
    egRobot1: "NONE" | "BACKSTAGE" | "RIGGING";
    egRobot2: "NONE" | "BACKSTAGE" | "RIGGING";
    drone1: number;
    drone2: number;
    minorPenalties: number;
    majorPenalties: number;
    autoNavigationPoints: number;
    autoRandomizationPoints: number;
    autoBackstagePoints: number;
    autoBackdropPoints: number;
    dcBackdropPoints: number;
    dcBackstagePoints: number;
    mosaicPoints: number;
    setBonusPoints: number;
    egLocationPoints: number;
    egDronePoints: number;
    autoPoints: number;
    dcPoints: number;
    endgamePoints: number;
    penaltyPointsCommitted: number;
    prePenaltyTotal: number;
    totalPoints: number;
}
