export enum AwardType {
    DeansListFinalist = "DeansListFinalist",
    DeansListSemiFinalist = "DeansListSemiFinalist",
    DeansListWinner = "DeansListWinner",
    JudgesChoice = "JudgesChoice",
    DivisionFinalist = "DivisionFinalist",
    DivisionWinner = "DivisionWinner",
    ConferenceFinalist = "ConferenceFinalist",
    Compass = "Compass",
    Promote = "Promote",
    Control = "Control",
    Motivate = "Motivate",
    Reach = "Reach",
    Sustain = "Sustain",
    Design = "Design",
    Innovate = "Innovate",
    Connect = "Connect",
    Think = "Think",
    TopRanked = "TopRanked",
    Inspire = "Inspire",
    Winner = "Winner",
    Finalist = "Finalist",
}
