export const RegionCode = {
    // cspell:disable
    AE: "AE",
    AR: "AR",
    AU: "AU",
    BR: "BR",
    CAAB: "CAAB",
    CABC: "CABC",
    CANL: "CANL",
    CAON: "CAON",
    CAQC: "CAQC",
    CMPIC: "CMPIC",
    CMPZ2: "CMPZ2",
    CN: "CN",
    CO: "CO",
    CY: "CY",
    DE: "DE",
    EC: "EC",
    ECB: "ECB",
    EG: "EG",
    ES: "ES",
    FPE: "FPE",
    FR: "FR",
    GB: "GB",
    GR: "GR",
    HKG: "HKG",
    HT: "HT",
    HU: "HU",
    ID: "ID",
    IL: "IL",
    IN: "IN",
    IND: "IND",
    IT: "IT",
    JM: "JM",
    JP: "JP",
    KR: "KR",
    KW: "KW",
    KZ: "KZ",
    LT: "LT",
    LY: "LY",
    MA: "MA",
    MD: "MD",
    MX: "MX",
    MY: "MY",
    NG: "NG",
    NL: "NL",
    NZ: "NZ",
    ONADOD: "ONADOD",
    PA: "PA",
    PL: "PL",
    PT: "PT",
    PY: "PY",
    QA: "QA",
    RO: "RO",
    RU: "RU",
    SA: "SA",
    SV: "SV",
    TH: "TH",
    TR: "TR",
    TT: "TT",
    TW: "TW",
    UA: "UA",
    USAK: "USAK",
    USAL: "USAL",
    USAR: "USAR",
    USARL: "USARL",
    USAZ: "USAZ",
    USCALA: "USCALA",
    USCALS: "USCALS",
    USCANO: "USCANO",
    USCASD: "USCASD",
    USCHS: "USCHS",
    USCO: "USCO",
    USCT: "USCT",
    USDE: "USDE",
    USFCT: "USFCT",
    USFL: "USFL",
    USGA: "USGA",
    USHI: "USHI",
    USIA: "USIA",
    USID: "USID",
    USIL: "USIL",
    USIN: "USIN",
    USKY: "USKY",
    USLA: "USLA",
    USMA: "USMA",
    USMD: "USMD",
    USMI: "USMI",
    USMN: "USMN",
    USMOKS: "USMOKS",
    USMS: "USMS",
    USMT: "USMT",
    USNC: "USNC",
    USND: "USND",
    USNE: "USNE",
    USNH: "USNH",
    USNJ: "USNJ",
    USNM: "USNM",
    USNV: "USNV",
    USNYEX: "USNYEX",
    USNYLI: "USNYLI",
    USNYNY: "USNYNY",
    USOH: "USOH",
    USOK: "USOK",
    USOR: "USOR",
    USPA: "USPA",
    USPR: "USPR",
    USRI: "USRI",
    USSC: "USSC",
    USTN: "USTN",
    USTXCE: "USTXCE",
    USTXHO: "USTXHO",
    USTXNO: "USTXNO",
    USTXSO: "USTXSO",
    USTXWP: "USTXWP",
    USUT: "USUT",
    USVA: "USVA",
    USVT: "USVT",
    USWA: "USWA",
    USWI: "USWI",
    USWV: "USWV",
    USWY: "USWY",
    VE: "VE",
    VN: "VN",
    ZA: "ZA",
    // cspell:enable
} as const;
export type RegionCode = (typeof RegionCode)[keyof typeof RegionCode];

export const RegionOption = {
    All: "All",
    UnitedStates: "UnitedStates",
    International: "International",
    // cspell:ignore USCA, USNY, USTX
    USCA: "USCA",
    USNY: "USNY",
    USTX: "USTX",
    ...RegionCode,
} as const;
export type RegionOption = (typeof RegionOption)[keyof typeof RegionOption];

export function getRegionCodes(region: RegionOption): RegionCode[] {
    switch (region) {
        case RegionOption.All:
            return Object.values(RegionCode);
        case RegionOption.UnitedStates:
            return Object.values(RegionCode).filter((c) => c.startsWith("US"));
        case RegionOption.International:
            return INTERNATIONAL_REGIONS;
        case RegionOption.USTX:
        case RegionOption.USCA:
        case RegionOption.USNY:
            return [
                ...Object.values(RegionCode).filter((c) => c.startsWith(region)),
                region,
            ] as any;
        default:
            return [region];
    }
}

export const INTERNATIONAL_REGIONS = [
    RegionOption.AE,
    RegionOption.AR,
    RegionOption.AU,
    RegionOption.BR,
    RegionOption.CN,
    RegionOption.CO,
    RegionOption.CY,
    RegionOption.DE,
    RegionOption.EC,
    RegionOption.ECB,
    RegionOption.EG,
    RegionOption.ES,
    RegionOption.FR,
    RegionOption.GB,
    RegionOption.GR,
    RegionOption.HKG,
    RegionOption.HT,
    RegionOption.HU,
    RegionOption.ID,
    RegionOption.IL,
    RegionOption.IN,
    RegionOption.IT,
    RegionOption.JM,
    RegionOption.JP,
    RegionOption.KR,
    RegionOption.KW,
    RegionOption.KZ,
    RegionOption.LT,
    RegionOption.LY,
    RegionOption.MA,
    RegionOption.MD,
    RegionOption.MX,
    RegionOption.MY,
    RegionOption.NG,
    RegionOption.NL,
    RegionOption.NZ,
    RegionOption.PA,
    RegionOption.PL,
    RegionOption.PT,
    RegionOption.PY,
    RegionOption.QA,
    RegionOption.RO,
    RegionOption.RU,
    RegionOption.SA,
    RegionOption.SV,
    RegionOption.TH,
    RegionOption.TR,
    RegionOption.TT,
    RegionOption.TW,
    RegionOption.UA,
    RegionOption.VE,
    RegionOption.VN,
    RegionOption.ZA,
];
